name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Fly.io Docker registry
        run: echo "${{ secrets.FLY_API_TOKEN }}" | docker login registry.fly.io -u x --password-stdin

      - name: Build Docker image
        run: |
          docker build -t registry.fly.io/upper49th:latest .

      - name: Push Docker image to Fly.io
        run: |
          docker push registry.fly.io/upper49th:latest

      - name: Deploy to Fly.io using prebuilt image
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly deploy --image registry.fly.io/upper49th:latest --app upper49th
